MvcTutorial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcTutorial.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcTutorial.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcTutorial/Controllers/StudyController.cs
using Microsoft.AspNetCore.Mvc;
using MvcTutorial.Data;
using MvcTutorial.Models;
using MvcTutorial.Models.View_Models;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace MvcTutorial.Controllers
{
    public class StudyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Hiragana()
        {
            return View();
        }

        public IActionResult Katakana()
        {
            return View();
        }
        
        public IActionResult StartStudy(string topicCode)
        {
            if (topicCode == null)
                return null;
            var session = StudySessionManager.NewSessionWithTopicCode(topicCode);
            var sessionKey = StudySessionManager.AddSession(session);

            var viewData = new QuestionViewModel(sessionKey, session.currentQuestion.question, session.QuestionsRemaining(), session.tutorialView, session.nextStudyLink);
            return View("Question", viewData);
        }

        /// <summary>
        /// Validates the user's answer, loads the next question and sends feedback to the user.
        /// </summary>
        /// <param name="sessionKey">The user's private session key.</param>
        /// <param name="answer">The user's answer to the current question.</param>
        /// <returns>The correct answer to the question.</returns>
        public string VerifyAnswer(string sessionKey, string answer)
        {
            answer = answer.ToLower();
            //Authentificate user and validate answer
            var guid = new Guid(sessionKey);
            var session = StudySessionManager.GetSession(guid);
            var answerExplanation = session.currentQuestion.answerExplanation;
            var correctAnswer = session.VerifyAnswer(answer);

            //Send correct answer back to user
            dynamic jsonResponse = new JObject();
            jsonResponse.correctAnswer = correctAnswer;
            jsonResponse.answerWasAccepted = (correctAnswer == answer);
            jsonResponse.questionsRemaining = session.QuestionsRemaining();
            jsonResponse.answerExplanation = answerExplanation;
            return Newtonsoft.Json.JsonConvert.SerializeObject(jsonResponse);
        }

        /// <summary>
        /// Gets the current question. Ends the study if all questions were answered.
        /// </summary>
        /// <param name="sessionKey">The user's private session key.</param>
        /// <returns>The next question. The question is empty if all questions have been answered.</returns>
        public string NextQuestion(string sessionKey)
        {
            //Authentificate user
            var guid = new Guid(sessionKey);
            var session = StudySessionManager.GetSession(guid);
            
            //Get next question
            string nextQuestion = "";
            if (session.studyComplete)
            {
                StudySessionManager.TerminateSession(guid);
            }
            else
            {
                nextQuestion = session.currentQuestion.question;
            }

            //Send next question to the user
            dynamic jsonResponse = new JObject();
            jsonResponse.question = nextQuestion;
            jsonResponse.tutorial = session.extraTutorialId;
            return Newtonsoft.Json.JsonConvert.SerializeObject(jsonResponse);
        }
    }
}

MvcTutorial/Views/Home/About.cshtml
@{
    ViewData["Title"] = "À propos";
}
<h1>@ViewData["Title"]</h1>
<p class="cropToCenter">
    Ce site web est un projet étudiant.
</p>
<br />

<div>
    <div class="box cropToCenter">
        <h3>Développé avec:</h3>
        <p>
            - ASP.NET MVC: <a href="https://dotnet.microsoft.com/apps/aspnet/mvc" class="colored-link">https://dotnet.microsoft.com/apps/aspnet/mvc</a> <br />
            - JQuery: <a href="https://jquery.com/" class="colored-link">https://jquery.com/</a> <br />
            <br />
            Hébergé sur Azure Websites: <a href="https://azure.microsoft.com/en-ca/" class="colored-link">https://azure.microsoft.com/en-ca/</a> <br />
        </p>
    </div><br /><br />

    <div class="box cropToCenter">
        <h3>Ressources utilisés:</h3>
        <p>
            <a href="https://commons.wikimedia.org/wiki/Hiragana" class="colored-link">Animations de traits des hiraganas</a> par <b>Sirgazil</b> <br />
        </p>
    </div><br /><br />

    <div class="box cropToCenter">
        <h3>Politique de confidentialité</h3>
        <p>
            Nous ne stockons pas vos données. <br />
            <br />
            Je ne sais pas comment placer des cookies, ni comment demander votre adresse courrielle. <br />
            Contactez-moi à pime2121@gmail.com pour toute question. <br />
        </p>
    </div><br /><br />
</div>

MvcTutorial/Views/Home/Index.cshtml
@{ 
    ViewData["Title"] = "Apprendre les kanas";
}

<div>
    <h1>Apprenons les kanas!</h1>
    <h3>Un site pour apprendre à lire et écrire le japonais, à partir de zéro.</h3>
    <div class="row">
        <div class="col-md-6">
            <div class="card text-bg-dark h-100">
                <div class="card-body">
                    <h1 class="card-title">Hiragana</h1>
                    <p class="card-text">La première étape pour apprendre à lire et écrire.</p>
                </div>
                <a asp-controller="Study" asp-action="Hiragana" class="btn btn-primary">Apprendre</a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card text-bg-dark h-100">
                <div class="card-body">
                    <h1 class="card-title">Katakana</h1>
                    <p class="card-text">Le deuxième « alphabet » utilisé en japonais.</p>
                </div>
                <a asp-controller="Study" asp-action="Katakana" class="btn btn-primary">Apprendre</a>
            </div>
        </div>
    </div>
</div>